name: Thunder âš¡ Build Apk

on: workflow_dispatch

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: LF gradlew line endings
        run: sed -i 's/\r$//' gradlew
        shell: bash

      - name: Build release APK
        run: bash gradlew assembleRelease
        shell: bash

      - name: Build release bundle
        run: bash gradlew bundleRelease
        shell: bash

      - name: Get tag
        id: tag
        run: |
          tag="$(git rev-parse --short HEAD)_$(date +%s)"
          echo "::set-output name=tag::$tag"
          commit_id=$(git ls-remote https://github.com/anujd64/Thunder.git HEAD | awk '{ print $1}')
          bodyx="#Changelog\n\n> https://github.com/anujd64/Thunder/commit/$commit_id"
          echo -e $bodyx > bodyx.txt
        shell: bash

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITUB_TOKEN }}
        with:
          tag_name: build-${{ steps.tag.outputs.tag }}
          release_name: Build ${{ steps.tag.outputs.tag }}
          body_path: "bodyx.txt"

      - name: Upload unsigned release APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/release/app-release-unsigned.apk
          asset_name: app-release-unsigned.apk
          asset_content_type: application/apk
      - name: Send unsigned release APK
        run: |
          curl -F document=@"./app/build/outputs/apk/release/app-release-unsigned.apk" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_TO }}&caption=unsigned

      - name: Upload release bundle
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/bundle/release/app-release.aab
          asset_name: app-release.aab
          asset_content_type: application/aab
      - name: Send release bundle
        run: |
          curl -F document=@"./app/build/outputs/bundle/release/app-release.aab" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_TO }}&caption=bundle

      - name: Fetch public keystore
        run: wget https://github.com/dishapatel010/Thunder/raw/Z/keystore.jks
        shell: bash

      - name: Sign release APK
        run: |
          apksigner="$(find $ANDROID_SDK_ROOT/build-tools -name apksigner | sort -r | head -n 1)"
          "$apksigner" sign --ks keystore.jks --ks-key-alias mydomain --ks-pass pass:password --key-pass pass:password --in ./app/build/outputs/apk/release/app-release-unsigned.apk --out ./app/build/outputs/apk/release/app-release.apk
        shell: bash

      - name: Upload signed release APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/apk
      - name: Send signed release APK
        run: |
          curl -F document=@"./app/build/outputs/apk/release/app-release.apk" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_TO }}&caption=signed
