name: Publish Release APK

on: workflow_dispatch

jobs:
  Gradle:
    runs-on: windows-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Generating debug keystore and SHA1 key
      shell: powershell
      run: |
        md C:\Users\runneradmin\.android
        keytool -genkey -dname "cn=Abhishek Dubey, ou=DSCBVPPUNE, o=Google, l=Pune, st=Maharashtra, c=IN" -keystore C:\Users\runneradmin\.android\debug.keystore -storepass android -alias AndroidDebugKey -keyalg RSA -keysize 4096 -validity 10000 -v
    - name: Displaying debug.keystore file
      shell: powershell
      run: keytool -list -v -keystore C:\Users\runneradmin\.android\debug.keystore -alias AndroidDebugKey -storepass android -keypass android
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        path: C:\Users\runneradmin\.android\debug.keystore
