name: Thunder âš¡ Build Apk

on: workflow_dispatch

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: LF gradlew line endings
        run: sed -i 's/\r$//' gradlew
        shell: bash

      - name: Build release APK
        run: bash gradlew assembleRelease
        shell: bash

      - name: Build release bundle
        run: bash gradlew bundleRelease
        shell: bash

      - name: Get tag
        id: tag
        run: |
          tag="$(git rev-parse --short HEAD)_$(date +%s)"
          echo "::set-output name=tag::$tag"
          commit_id=$(git ls-remote https://github.com/anujd64/Thunder.git HEAD | awk '{ print $1}')
          bodyx="# Changelog\n\n> https://github.com/anujd64/Thunder/commit/$commit_id"
          echo -e $bodyx > bodyx.txt
        shell: bash

      - name: Fetch public keystore
        run: wget https://github.com/dishapatel010/Thunder/raw/Z/keystore.jks
        shell: bash

      - name: Sign release APK
        run: |
          apksigner="$(find $ANDROID_SDK_ROOT/build-tools -name apksigner | sort -r | head -n 1)"
          "$apksigner" sign --ks keystore.jks --ks-key-alias mydomain --ks-pass pass:password --key-pass pass:password --in ./app/build/outputs/apk/release/app-release-unsigned.apk --out ./app/build/outputs/apk/release/app-release.apk
        shell: bash
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITUB_TOKEN }}
        with:
          tag_name: build-${{ steps.tag.outputs.tag }}
          name: Build ${{ steps.tag.outputs.tag }}
          draft: true
          body_path: "bodyx.txt"
          files: ./app/build/outputs/apk/release/*.apk
